name: CI DEMO

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      name: Git clone repo code
      uses: actions/checkout@v4

      name: BUN or NPM
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.3.3
      
      -run: bun install
      -run: echo "Success"